version: '3'
services:
  core-postgres:
    image: postgres:9.6.17-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockchain-core
      - PGDATA=/tmp
    expose:
      - "6432"
    command: "-p 6432"
    volumes:
      - "./core-db-data:/var/lib/postgresql/data"

  core:
    image: interstellartech/blockchain-core:4
    depends_on:
      - core-postgres
    restart: on-failure
    expose:
      - "11626"
    ports:
      - "11625:11625"
    command: run
    volumes:
      - "./bantu-mainnet.cfg:/blockchain-core.cfg"
      - "./blockchain-data:/blockchain-data"


volumes:
  core-db-data:
  blockchain-data:

